module FilterHelper
	def filter(company_id ,donor,test_type_id, result, date_created_inicio, date_created_fim, scheduled_inicio, scheduled_fim)
		if test_type_id.blank? and result.blank? and date_created_inicio.blank? and date_created_fim.blank? and scheduled_inicio.blank? and scheduled_fim.blank? and donor.blank?
	      @selected_tests = SelectedTest.joins("INNER JOIN drug_tests on selected_tests.drug_test_id = drug_tests.id INNER JOIN donors on donors.id = drug_tests.donor_id INNER JOIN users on users.company_id= donors.company_id INNER JOIN test_types on  selected_tests.test_type_id = test_types.id").where("users.company_id = ?",company_id )
	    elsif test_type_id != "" and result.blank? and date_created_inicio.blank? and date_created_fim.blank? and scheduled_inicio.blank? and scheduled_fim.blank? and donor.blank?
	      @selected_tests = SelectedTest.joins("INNER JOIN drug_tests on selected_tests.drug_test_id = drug_tests.id INNER JOIN donors on donors.id = drug_tests.donor_id INNER JOIN users on users.company_id= donors.company_id INNER JOIN test_types on  selected_tests.test_type_id = test_types.id").where("users.company_id = ? AND test_types.id = ?", company_id , test_type_id) 
	    elsif result != "" and test_type_id.blank? and date_created_inicio.blank? and date_created_fim.blank? and scheduled_inicio.blank? and scheduled_fim.blank? and donor.blank?
	      @selected_tests = SelectedTest.joins("INNER JOIN drug_tests on selected_tests.drug_test_id = drug_tests.id INNER JOIN donors on donors.id = drug_tests.donor_id INNER JOIN users on users.company_id= donors.company_id INNER JOIN test_types on  selected_tests.test_type_id = test_types.id").where("users.company_id = ? AND selected_tests.result = ?", company_id  , result)
	    elsif result != "" and test_type_id != "" and date_created_inicio.blank? and date_created_fim.blank? and scheduled_inicio.blank? and scheduled_fim.blank? and donor.blank?
	      @selected_tests = SelectedTest.joins("INNER JOIN drug_tests on selected_tests.drug_test_id = drug_tests.id INNER JOIN donors on donors.id = drug_tests.donor_id INNER JOIN users on users.company_id= donors.company_id INNER JOIN test_types on  selected_tests.test_type_id = test_types.id").where("users.company_id = ? AND test_types.id = ? AND selected_tests.result = ?" , company_id , test_type_id, result)
	    elsif date_created_inicio != "" and date_created_fim.blank? and scheduled_inicio.blank? and scheduled_fim.blank? and test_type_id.blank? and result.blank? and donor.blank?
	      @selected_tests = SelectedTest.joins("INNER JOIN drug_tests on selected_tests.drug_test_id = drug_tests.id INNER JOIN donors on donors.id = drug_tests.donor_id INNER JOIN users on users.company_id= donors.company_id INNER JOIN test_types on  selected_tests.test_type_id = test_types.id").where("users.company_id = ? AND selected_tests.created_at >= ?", company_id , date_created_inicio)
	    elsif date_created_fim != "" and date_created_inicio.blank? and scheduled_inicio.blank? and scheduled_fim.blank? and test_type_id.blank? and result.blank? and donor.blank?
	      @selected_tests = SelectedTest.joins("INNER JOIN drug_tests on selected_tests.drug_test_id = drug_tests.id INNER JOIN donors on donors.id = drug_tests.donor_id INNER JOIN users on users.company_id= donors.company_id INNER JOIN test_types on  selected_tests.test_type_id = test_types.id").where("users.company_id = ? AND selected_tests.created_at <= ?", company_id , date_created_fim)
	    elsif date_created_inicio != "" and date_created_fim != "" and scheduled_inicio.blank? and scheduled_fim.blank? and test_type_id.blank? and result.blank? and donor.blank?
	      @selected_tests = SelectedTest.joins("INNER JOIN drug_tests on selected_tests.drug_test_id = drug_tests.id INNER JOIN donors on donors.id = drug_tests.donor_id INNER JOIN users on users.company_id= donors.company_id INNER JOIN test_types on  selected_tests.test_type_id = test_types.id").where("users.company_id = ? AND selected_tests.created_at >= ? AND selected_tests.created_at <= ?", company_id , date_created_inicio, date_created_fim) 
	    elsif scheduled_inicio != "" and scheduled_fim.blank? and result.blank? and test_type_id.blank? and date_created_inicio.blank? and date_created_fim.blank? and donor.blank? 
	      @selected_tests = SelectedTest.joins("INNER JOIN drug_tests on selected_tests.drug_test_id = drug_tests.id INNER JOIN donors on donors.id = drug_tests.donor_id INNER JOIN users on users.company_id= donors.company_id INNER JOIN test_types on  selected_tests.test_type_id = test_types.id").where("users.company_id = ? AND drug_tests.scheduled_to >= ?", company_id , scheduled_inicio)
	    elsif scheduled_fim != "" and scheduled_inicio.blank? and result.blank? and test_type_id.blank? and date_created_inicio.blank? and date_created_fim.blank? and donor.blank? 
	      @selected_tests = SelectedTest.joins("INNER JOIN drug_tests on selected_tests.drug_test_id = drug_tests.id INNER JOIN donors on donors.id = drug_tests.donor_id INNER JOIN users on users.company_id= donors.company_id INNER JOIN test_types on  selected_tests.test_type_id = test_types.id").where("users.company_id = ? AND drug_tests.scheduled_to <= ?" , company_id , scheduled_fim)
	    elsif scheduled_inicio != "" and scheduled_fim != "" and result.blank? and test_type_id.blank? and date_created_inicio.blank? and date_created_fim.blank? and donor.blank? 
	      @selected_tests = SelectedTest.joins("INNER JOIN drug_tests on selected_tests.drug_test_id = drug_tests.id INNER JOIN donors on donors.id = drug_tests.donor_id INNER JOIN users on users.company_id= donors.company_id INNER JOIN test_types on  selected_tests.test_type_id = test_types.id").where("users.company_id = ? AND drug_tests.scheduled_to >= ? AND drug_tests.scheduled_to <= ?" , company_id , scheduled_inicio, scheduled_fim)
	    elsif test_type_id != "" and date_created_inicio != "" and date_created_fim.blank? and scheduled_inicio.blank? and scheduled_fim.blank? and result.blank? and donor.blank?
	      @selected_tests = SelectedTest.joins("INNER JOIN drug_tests on selected_tests.drug_test_id = drug_tests.id INNER JOIN donors on donors.id = drug_tests.donor_id INNER JOIN users on users.company_id= donors.company_id INNER JOIN test_types on  selected_tests.test_type_id = test_types.id").where("users.company_id = ? AND test_types.id = ? AND selected_tests.created_at >= ?", company_id  , test_type_id , date_created_inicio)
	    elsif test_type_id != "" and date_created_inicio != "" and date_created_fim != "" and scheduled_inicio.blank? and scheduled_fim.blank? and result.blank? and donor.blank?
	      @selected_tests = SelectedTest.joins("INNER JOIN drug_tests on selected_tests.drug_test_id = drug_tests.id INNER JOIN donors on donors.id = drug_tests.donor_id INNER JOIN users on users.company_id= donors.company_id INNER JOIN test_types on  selected_tests.test_type_id = test_types.id").where("users.company_id = ? AND test_types.id = ? AND selected_tests.created_at >= ? AND selected_tests.created_at <= ?", company_id  , test_type_id, date_created_inicio, date_created_fim)
	    elsif test_type_id != "" and date_created_inicio.blank? and date_created_fim != "" and scheduled_inicio.blank? and scheduled_fim.blank? and result.blank? and donor.blank?
	      @selected_tests = SelectedTest.joins("INNER JOIN drug_tests on selected_tests.drug_test_id = drug_tests.id INNER JOIN donors on donors.id = drug_tests.donor_id INNER JOIN users on users.company_id= donors.company_id INNER JOIN test_types on  selected_tests.test_type_id = test_types.id").where("users.company_id = ? AND test_types.id = ? AND selected_tests.created_at <= ?" , company_id  , test_type_id, date_created_fim)
	    elsif test_type_id != "" and date_created_inicio.blank? and date_created_fim.blank? and scheduled_inicio.blank?  and scheduled_fim != "" and result.blank? and donor.blank?
	      @selected_tests = SelectedTest.joins("INNER JOIN drug_tests on selected_tests.drug_test_id = drug_tests.id INNER JOIN donors on donors.id = drug_tests.donor_id INNER JOIN users on users.company_id= donors.company_id INNER JOIN test_types on  selected_tests.test_type_id = test_types.id").where("users.company_id = ? AND test_types.id = ? AND drug_tests.scheduled_to <= ?", company_id  , test_type_id, scheduled_fim)
	    elsif test_type_id != "" and date_created_inicio.blank? and date_created_fim.blank? and scheduled_inicio != "" and scheduled_fim.blank? and result.blank? and donor.blank?
	      @selected_tests = SelectedTest.joins("INNER JOIN drug_tests on selected_tests.drug_test_id = drug_tests.id INNER JOIN donors on donors.id = drug_tests.donor_id INNER JOIN users on users.company_id= donors.company_id INNER JOIN test_types on  selected_tests.test_type_id = test_types.id").where("users.company_id = ? AND test_types.id = ? AND drug_tests.scheduled_to >= ?", company_id  , test_type_id, scheduled_inicio)
	    elsif test_type_id != "" and date_created_inicio.blank? and date_created_fim.blank? and scheduled_inicio  != "" and scheduled_fim  != "" and result.blank? and donor.blank?
	      @selected_tests = SelectedTest.joins("INNER JOIN drug_tests on selected_tests.drug_test_id = drug_tests.id INNER JOIN donors on donors.id = drug_tests.donor_id INNER JOIN users on users.company_id= donors.company_id INNER JOIN test_types on  selected_tests.test_type_id = test_types.id").where("users.company_id = ? AND test_types.id = ? AND drug_tests.scheduled_to >= ?  AND drug_tests.scheduled_to <= ?", company_id  , test_type_id, scheduled_inicio, scheduled_fim)
	    elsif result != "" and test_type_id.blank? and date_created_inicio != "" and date_created_fim.blank? and scheduled_inicio.blank? and scheduled_fim.blank? and donor.blank? 
	      @selected_tests = SelectedTest.joins("INNER JOIN drug_tests on selected_tests.drug_test_id = drug_tests.id INNER JOIN donors on donors.id = drug_tests.donor_id INNER JOIN users on users.company_id= donors.company_id INNER JOIN test_types on  selected_tests.test_type_id = test_types.id").where("users.company_id = ? AND selected_tests.result = ? AND selected_tests.created_at >= ?" , company_id  , result, date_created_inicio)
	    elsif result != "" and test_type_id.blank? and date_created_inicio.blank? and date_created_fim != "" and scheduled_inicio.blank? and scheduled_fim.blank?and donor.blank? 
	      @selected_tests = SelectedTest.joins("INNER JOIN drug_tests on selected_tests.drug_test_id = drug_tests.id INNER JOIN donors on donors.id = drug_tests.donor_id INNER JOIN users on users.company_id= donors.company_id INNER JOIN test_types on  selected_tests.test_type_id = test_types.id").where("users.company_id = ? AND selected_tests.result = ? AND selected_tests.created_at <= ?" , company_id  , result, date_created_fim)
	    elsif result != "" and test_type_id.blank? and date_created_inicio != "" and date_created_fim != "" and scheduled_inicio.blank? and scheduled_fim.blank? and donor.blank?
	      @selected_tests = SelectedTest.joins("INNER JOIN drug_tests on selected_tests.drug_test_id = drug_tests.id INNER JOIN donors on donors.id = drug_tests.donor_id INNER JOIN users on users.company_id= donors.company_id INNER JOIN test_types on  selected_tests.test_type_id = test_types.id").where("users.company_id = ? AND selected_tests.result = ? AND selected_tests.created_at >= ? AND selected_tests.created_at <= ?" , company_id  , result, date_created_inicio, date_created_fim)
	    elsif result != "" and test_type_id.blank? and date_created_inicio.blank? and date_created_fim.blank? and scheduled_inicio.blank?  and scheduled_fim != "" and donor.blank?
	      @selected_tests = SelectedTest.joins("INNER JOIN drug_tests on selected_tests.drug_test_id = drug_tests.id INNER JOIN donors on donors.id = drug_tests.donor_id INNER JOIN users on users.company_id= donors.company_id INNER JOIN test_types on  selected_tests.test_type_id = test_types.id").where("users.company_id = ? AND selected_tests.result = ? AND drug_tests.scheduled_to <= ?", company_id  , result, scheduled_fim)
	    elsif result != "" and  test_type_id.blank? and date_created_inicio.blank? and date_created_fim.blank? and scheduled_inicio != "" and scheduled_fim.blank? and donor.blank?
	      @selected_tests = SelectedTest.joins("INNER JOIN drug_tests on selected_tests.drug_test_id = drug_tests.id INNER JOIN donors on donors.id = drug_tests.donor_id INNER JOIN users on users.company_id= donors.company_id INNER JOIN test_types on  selected_tests.test_type_id = test_types.id").where("users.company_id = ? AND selected_tests.result = ? AND drug_tests.scheduled_to >= ?", company_id  , result, scheduled_inicio)
	    elsif result != "" and test_type_id.blank? and date_created_inicio.blank? and date_created_fim.blank? and scheduled_inicio  != "" and scheduled_fim  != "" and donor.blank?
	      @selected_tests = SelectedTest.joins("INNER JOIN drug_tests on selected_tests.drug_test_id = drug_tests.id INNER JOIN donors on donors.id = drug_tests.donor_id INNER JOIN users on users.company_id= donors.company_id INNER JOIN test_types on  selected_tests.test_type_id = test_types.id").where("users.company_id = ? AND selected_tests.result = ? AND drug_tests.scheduled_to >= ? AND drug_tests.scheduled_to <= ?" ,company_id  , result, scheduled_inicio, scheduled_fim)
	    elsif result != "" and test_type_id !="" and date_created_inicio != "" and date_created_fim.blank? and scheduled_inicio.blank? and scheduled_fim.blank? and donor.blank?
	      @selected_tests = SelectedTest.joins("INNER JOIN drug_tests on selected_tests.drug_test_id = drug_tests.id INNER JOIN donors on donors.id = drug_tests.donor_id INNER JOIN users on users.company_id= donors.company_id INNER JOIN test_types on  selected_tests.test_type_id = test_types.id").where("users.company_id = ? AND test_types.id = ? AND selected_tests.result = ? AND selected_tests.created_at >= ?" , company_id  , test_type_id, result, date_created_inicio)
	    elsif result != "" and test_type_id !="" and date_created_inicio.blank? and date_created_fim != "" and scheduled_inicio.blank? and scheduled_fim.blank? and donor.blank?
	      @selected_tests = SelectedTest.joins("INNER JOIN drug_tests on selected_tests.drug_test_id = drug_tests.id INNER JOIN donors on donors.id = drug_tests.donor_id INNER JOIN users on users.company_id= donors.company_id INNER JOIN test_types on  selected_tests.test_type_id = test_types.id").where("users.company_id = ? AND test_types.id = ? AND selected_tests.result = ? AND selected_tests.created_at <= ?", company_id  , test_type_id, result, date_created_fim)
	    elsif result != "" and test_type_id !="" and date_created_inicio != "" and date_created_fim != "" and scheduled_inicio.blank? and scheduled_fim.blank? and donor.blank?
	      @selected_tests = SelectedTest.joins("INNER JOIN drug_tests on selected_tests.drug_test_id = drug_tests.id INNER JOIN donors on donors.id = drug_tests.donor_id INNER JOIN users on users.company_id= donors.company_id INNER JOIN test_types on  selected_tests.test_type_id = test_types.id").where("users.company_id = ? AND test_types.id = ? AND selected_tests.result = ? AND selected_tests.created_at >= ? AND selected_tests.created_at <= ?", company_id  , test_type_id, result, date_created_inicio, date_created_fim)
	    elsif result != "" and test_type_id !="" and date_created_inicio.blank? and date_created_fim.blank? and scheduled_inicio.blank?  and scheduled_fim != "" and donor.blank?
	      @selected_tests = SelectedTest.joins("INNER JOIN drug_tests on selected_tests.drug_test_id = drug_tests.id INNER JOIN donors on donors.id = drug_tests.donor_id INNER JOIN users on users.company_id= donors.company_id INNER JOIN test_types on  selected_tests.test_type_id = test_types.id").where("users.company_id = ? AND test_types.id = ? AND selected_tests.result = ? AND drug_tests.scheduled_to <= ?",  company_id  , test_type_id, result, scheduled_fim)
	    elsif result != "" and  test_type_id !="" and date_created_inicio.blank? and date_created_fim.blank? and scheduled_inicio != "" and scheduled_fim.blank? and donor.blank?
	      @selected_tests = SelectedTest.joins("INNER JOIN drug_tests on selected_tests.drug_test_id = drug_tests.id INNER JOIN donors on donors.id = drug_tests.donor_id INNER JOIN users on users.company_id= donors.company_id INNER JOIN test_types on  selected_tests.test_type_id = test_types.id").where("users.company_id = ? AND test_types.id = ? AND selected_tests.result = ? AND drug_tests.scheduled_to >= ?", company_id  , test_type_id, result, scheduled_inicio)
	    elsif result != "" and test_type_id !="" and date_created_inicio.blank? and date_created_fim.blank? and scheduled_inicio  != "" and scheduled_fim  != "" and donor.blank?
	      @selected_tests = SelectedTest.joins("INNER JOIN drug_tests on selected_tests.drug_test_id = drug_tests.id INNER JOIN donors on donors.id = drug_tests.donor_id INNER JOIN users on users.company_id= donors.company_id INNER JOIN test_types on  selected_tests.test_type_id = test_types.id").where("users.company_id = ? AND test_types.id = ? AND selected_tests.result = ? AND drug_tests.scheduled_to >= ? AND drug_tests.scheduled_to <= ?", company_id  , test_type_id, result, scheduled_inicio, scheduled_fim)
	    elsif result != "" and test_type_id !="" and date_created_inicio != "" and date_created_fim.blank? and scheduled_inicio != "" and scheduled_fim != "" and donor.blank?
	      @selected_tests = SelectedTest.joins("INNER JOIN drug_tests on selected_tests.drug_test_id = drug_tests.id INNER JOIN donors on donors.id = drug_tests.donor_id INNER JOIN users on users.company_id= donors.company_id INNER JOIN test_types on  selected_tests.test_type_id = test_types.id").where("users.company_id = ? AND test_types.id = ? AND selected_tests.result = ? AND selected_tests.created_at >= ? AND drug_tests.scheduled_to >= ? AND drug_tests.scheduled_to <= ?", company_id  , test_type_id, result, date_created_inicio , scheduled_inicio, scheduled_fim)
	    elsif result != "" and test_type_id !="" and date_created_inicio.blank? and date_created_fim != "" and scheduled_inicio != "" and scheduled_fim != "" and donor.blank?
	      @selected_tests = SelectedTest.joins("INNER JOIN drug_tests on selected_tests.drug_test_id = drug_tests.id INNER JOIN donors on donors.id = drug_tests.donor_id INNER JOIN users on users.company_id= donors.company_id INNER JOIN test_types on  selected_tests.test_type_id = test_types.id").where("users.company_id = ? AND test_types.id = ? AND selected_tests.result = ? AND selected_tests.created_at <= ? AND drug_tests.scheduled_to >= ? AND drug_tests.scheduled_to <= ?", company_id  , test_type_id, result, date_created_fim, scheduled_inicio, scheduled_fim)
	    elsif result != "" and test_type_id !="" and date_created_inicio != "" and date_created_fim != "" and scheduled_inicio.blank?  and scheduled_fim != "" and donor.blank?
	      @selected_tests = SelectedTest.joins("INNER JOIN drug_tests on selected_tests.drug_test_id = drug_tests.id INNER JOIN donors on donors.id = drug_tests.donor_id INNER JOIN users on users.company_id= donors.company_id INNER JOIN test_types on  selected_tests.test_type_id = test_types.id").where("users.company_id = ? AND test_types.id = ? AND selected_tests.result = ? AND selected_tests.created_at >= ? AND selected_tests.created_at <= ? AND drug_tests.scheduled_to <= ?", company_id  , test_type_id, result, date_created_inicio, date_created_fim, scheduled_fim)
	    elsif result != "" and  test_type_id !="" and date_created_inicio != "" and date_created_fim != "" and scheduled_inicio != "" and scheduled_fim.blank? and donor.blank?
	      @selected_tests = SelectedTest.joins("INNER JOIN drug_tests on selected_tests.drug_test_id = drug_tests.id INNER JOIN donors on donors.id = drug_tests.donor_id INNER JOIN users on users.company_id= donors.company_id INNER JOIN test_types on  selected_tests.test_type_id = test_types.id").where("users.company_id = ? AND test_types.id = ? AND selected_tests.result = ? AND selected_tests.created_at >= ? AND selected_tests.created_at <= ? AND drug_tests.scheduled_to >= ?", company_id  , test_type_id, result, date_created_inicio, date_created_fim, scheduled_inicio)
	    elsif result != "" and test_type_id !="" and date_created_inicio != "" and date_created_fim != "" and scheduled_inicio  != "" and scheduled_fim  != "" and donor != ""
	      @selected_tests = SelectedTest.joins("INNER JOIN drug_tests on selected_tests.drug_test_id = drug_tests.id INNER JOIN donors on donors.id = drug_tests.donor_id INNER JOIN users on users.company_id= donors.company_id INNER JOIN test_types on  selected_tests.test_type_id = test_types.id").where("users.company_id = ? AND selected_tests.created_at >= ? AND selected_tests.created_at <= ? AND test_types.id = ?  AND selected_tests.result = ?  AND drug_tests.scheduled_to >= ? AND drug_tests.scheduled_to <= ? AND drug_tests.donor_id = ?", company_id  , date_created_inicio ,date_created_fim, test_type_id, result, scheduled_inicio, scheduled_fim, donor)
	    elsif test_type_id.blank? and result.blank? and date_created_inicio.blank? and date_created_fim.blank? and scheduled_inicio.blank? and scheduled_fim.blank? and donor  != ""
	      @selected_tests = SelectedTest.joins("INNER JOIN drug_tests on selected_tests.drug_test_id = drug_tests.id INNER JOIN donors on donors.id = drug_tests.donor_id INNER JOIN users on users.company_id= donors.company_id INNER JOIN test_types on  selected_tests.test_type_id = test_types.id").where("users.company_id = ? AND drug_tests.donor_id = ?", company_id , donor) 
	    elsif test_type_id != "" and result.blank? and date_created_inicio.blank? and date_created_fim.blank? and scheduled_inicio.blank? and scheduled_fim.blank? and donor != ""
	      @selected_tests = SelectedTest.joins("INNER JOIN drug_tests on selected_tests.drug_test_id = drug_tests.id INNER JOIN donors on donors.id = drug_tests.donor_id INNER JOIN users on users.company_id= donors.company_id INNER JOIN test_types on  selected_tests.test_type_id = test_types.id").where("users.company_id = ? AND test_types.id = ? AND  drug_tests.donor_id = ?", company_id , test_type_id, donor) 
	    elsif result != "" and test_type_id != "" and date_created_inicio.blank? and date_created_fim.blank? and scheduled_inicio.blank? and scheduled_fim.blank? and donor != ""
	      @selected_tests = SelectedTest.joins("INNER JOIN drug_tests on selected_tests.drug_test_id = drug_tests.id INNER JOIN donors on donors.id = drug_tests.donor_id INNER JOIN users on users.company_id= donors.company_id INNER JOIN test_types on  selected_tests.test_type_id = test_types.id").where("users.company_id = ? AND test_types.id = ? AND  drug_tests.donor_id = ? AND selected_tests.result = ?" , company_id , test_type_id, result, donor)
	    elsif result != "" and donor != "" and test_type_id.blank? and date_created_inicio.blank? and date_created_fim.blank? and scheduled_inicio.blank? and scheduled_fim.blank? 
	      @selected_tests = SelectedTest.joins("INNER JOIN drug_tests on selected_tests.drug_test_id = drug_tests.id INNER JOIN donors on donors.id = drug_tests.donor_id INNER JOIN users on users.company_id= donors.company_id INNER JOIN test_types on  selected_tests.test_type_id = test_types.id").where("users.company_id = ? AND  drug_tests.donor_id = ? AND selected_tests.result = ?" , company_id , donor, result)
	   else
	      @selected_tests = SelectedTest.joins("INNER JOIN drug_tests on selected_tests.drug_test_id = drug_tests.id INNER JOIN donors on donors.id = drug_tests.donor_id INNER JOIN users on users.company_id= donors.company_id INNER JOIN test_types on  selected_tests.test_type_id = test_types.id").where("users.company_id = ? AND test_types.id= ?", company_id  ,"foradosfiltros" )
	   end
	end
end
