# encoding: UTF-8
# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
Company.create({legal_identifier: 12345678987654,legal_name: "ECO ESCREENING LTDA",trade_name:"Eco Escreening",contact_email:"developers@geeksgroup.com.br",contact_phone:"93284982374",contact_name:"Lucas",address:"Rua dois, 098",address_neighbourhood: "Bairro da Conquista",city_id: 123})

User.create({name: "Marcelo Silveira", email:"marcelo@orbitae.com.br",password: "ecos@2013",company_id: 1, role: "Administrador", admin: true})

Company.create({legal_identifier: 12323456435764,legal_name: "Empresa Ficticia Ltda",trade_name:"Empresa 1",contact_email:"developers@geeksgroup.com.br",contact_phone:"93284982374",contact_name:"Hiram",address:"Rua dos guajajaras, 910 - sl 1404",address_neighbourhood: "Bairro de Lourdes ",city_id: 1163})

User.create({name: "Hiram Castelo", email:"hiram@geeksgroup.com.br",password: "ecos@2013",company_id: 2, role: "Gerente"})
# donors
Donor.create({company_id: 2, name: 'Isabella Silva', legal_identifier: '860.146.739-92', document_type: :cpf,  birth_date: '1947-01-26'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Bernardo Ferreira', legal_identifier: '161.247.357-68', document_type: :cpf,  birth_date: '1968-02-04'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Maria Costela', legal_identifier: '928.590.140-10', document_type: :cpf,  birth_date: '1970-01-07'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Gabriela Barros', legal_identifier: '712.333.601-27', document_type: :cpf,  birth_date: '1988-08-20'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Mariana Pereira', legal_identifier: '226.949.623-42', document_type: :cpf,  birth_date: '1984-08-10'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Rafaela Oliveira', legal_identifier: '618.761.576-39', document_type: :cpf,  birth_date: '1969-05-14'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Nicolas Barros', legal_identifier: '174.686.657-20', document_type: :cpf,  birth_date: '1961-04-09'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Miguel Pereira', legal_identifier: '639.497.439-31', document_type: :cpf,  birth_date: '1986-01-16'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Enzo Cardoso', legal_identifier: '850.896.298-86', document_type: :cpf,  birth_date: '1980-01-09'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Manuela Correia', legal_identifier: '525.125.189-16', document_type: :cpf,  birth_date: '1975-03-30'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Giovanna Souza', legal_identifier: '285.799.898-58', document_type: :cpf,  birth_date: '1981-11-03'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Beatriz Costela', legal_identifier: '323.308.260-41', document_type: :cpf,  birth_date: '1983-06-04'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Julia Cardoso', legal_identifier: '302.991.890-42', document_type: :cpf,  birth_date: '1966-01-11'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Beatriz Almeida', legal_identifier: '734.130.957-98', document_type: :cpf,  birth_date: '1950-06-01'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Maria Barros', legal_identifier: '586.944.744-46', document_type: :cpf,  birth_date: '1971-12-13'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Isabella Fernandes', legal_identifier: '424.593.916-67', document_type: :cpf,  birth_date: '1971-12-20'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Arthur Gomes', legal_identifier: '103.161.156-65', document_type: :cpf,  birth_date: '1986-09-15'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Miguel Silva', legal_identifier: '170.778.804-98', document_type: :cpf,  birth_date: '1970-06-17'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Gustavo Castro', legal_identifier: '195.229.839-21', document_type: :cpf,  birth_date: '1958-10-28'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Isabella Ribeiro', legal_identifier: '320.202.537-90', document_type: :cpf,  birth_date: '1963-09-13'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Laura Barros', legal_identifier: '368.901.943-61', document_type: :cpf,  birth_date: '1949-09-28'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Arthur Alves', legal_identifier: '582.217.334-37', document_type: :cpf,  birth_date: '1953-11-29'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Julia Fernandes', legal_identifier: '286.402.828-79', document_type: :cpf,  birth_date: '1962-08-19'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Alice Ribeiro', legal_identifier: '506.720.992-20', document_type: :cpf,  birth_date: '1951-10-14'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Gabriela Carvalho', legal_identifier: '107.261.934-76', document_type: :cpf,  birth_date: '1964-12-11'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Bernardo Almeida', legal_identifier: '521.586.258-17', document_type: :cpf,  birth_date: '1948-02-24'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Yasmin Oliveira', legal_identifier: '322.159.370-66', document_type: :cpf,  birth_date: '1981-08-01'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Miguel Barros', legal_identifier: '446.848.554-41', document_type: :cpf,  birth_date: '1943-04-08'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Rafaela Cunha', legal_identifier: '857.375.983-73', document_type: :cpf,  birth_date: '1987-04-22'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Gabriela Oliveira', legal_identifier: '694.271.230-58', document_type: :cpf,  birth_date: '1957-02-19'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Guilherme Ferreira', legal_identifier: '906.236.695-93', document_type: :cpf,  birth_date: '1960-12-07'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Nicolas Barros', legal_identifier: '144.666.205-34', document_type: :cpf,  birth_date: '1943-03-05'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Miguel Silva', legal_identifier: '507.402.730-37', document_type: :cpf,  birth_date: '1978-12-18'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Matheus Souza', legal_identifier: '925.477.110-74', document_type: :cpf,  birth_date: '1959-12-07'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Giovanna Martins', legal_identifier: '608.469.800-15', document_type: :cpf,  birth_date: '1981-03-02'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Enzo Fernandes', legal_identifier: '379.610.780-37', document_type: :cpf,  birth_date: '1982-04-10'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Gabriela Pereira', legal_identifier: '581.343.227-88', document_type: :cpf,  birth_date: '1987-05-20'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Pedro Correia', legal_identifier: '636.480.992-27', document_type: :cpf,  birth_date: '1961-03-11'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Arthur Rodrigues', legal_identifier: '927.159.169-40', document_type: :cpf,  birth_date: '1968-02-17'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Lucas Almeida', legal_identifier: '233.864.885-14', document_type: :cpf,  birth_date: '1944-07-17'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Bernardo Oliveira', legal_identifier: '282.235.783-46', document_type: :cpf,  birth_date: '1979-11-05'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Isabella Barros', legal_identifier: '658.510.935-92', document_type: :cpf,  birth_date: '1977-10-26'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Rafael Correia', legal_identifier: '873.788.954-96', document_type: :cpf,  birth_date: '1972-03-19'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Luiza Gomes', legal_identifier: '266.878.892-56', document_type: :cpf,  birth_date: '1971-12-02'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Pedro Barros', legal_identifier: '814.766.522-90', document_type: :cpf,  birth_date: '1954-02-12'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Felipe Gomes', legal_identifier: '737.134.721-77', document_type: :cpf,  birth_date: '1989-09-02'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Sophia Santos', legal_identifier: '774.260.658-81', document_type: :cpf,  birth_date: '1981-03-17'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Rafael Rodrigues', legal_identifier: '486.259.137-98', document_type: :cpf,  birth_date: '1964-08-24'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Maria Cunha', legal_identifier: '159.895.461-82', document_type: :cpf,  birth_date: '1966-07-20'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Manuela Santos', legal_identifier: '664.580.384-28', document_type: :cpf,  birth_date: '1946-12-24'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Maria Melo', legal_identifier: '559.197.671-21', document_type: :cpf,  birth_date: '1948-07-27'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Manuela Souza', legal_identifier: '191.345.349-95', document_type: :cpf,  birth_date: '1949-02-13'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Davi Silva', legal_identifier: '799.698.960-86', document_type: :cpf,  birth_date: '1961-01-13'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Mariana Cardoso', legal_identifier: '912.547.637-88', document_type: :cpf,  birth_date: '1957-04-06'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Yasmin Pereira', legal_identifier: '764.119.953-54', document_type: :cpf,  birth_date: '1942-11-15'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Felipe Araújo', legal_identifier: '752.630.142-33', document_type: :cpf,  birth_date: '1974-02-23'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Lucas Costela', legal_identifier: '573.450.594-33', document_type: :cpf,  birth_date: '1944-10-27'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Pedro Santos', legal_identifier: '348.830.457-77', document_type: :cpf,  birth_date: '1942-01-27'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Giovanna Melo', legal_identifier: '270.505.970-50', document_type: :cpf,  birth_date: '1988-02-27'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Yasmin Barros', legal_identifier: '906.649.815-81', document_type: :cpf,  birth_date: '1978-02-22'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Manuela Rodrigues', legal_identifier: '683.994.394-74', document_type: :cpf,  birth_date: '1969-05-08'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Davi Almeida', legal_identifier: '364.228.177-77', document_type: :cpf,  birth_date: '1958-04-13'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Laura Azevedo', legal_identifier: '532.631.760-41', document_type: :cpf,  birth_date: '1945-07-30'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Rafaela Cardoso', legal_identifier: '640.768.473-33', document_type: :cpf,  birth_date: '1965-05-14'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Luiza Araújo', legal_identifier: '707.872.486-75', document_type: :cpf,  birth_date: '1963-09-26'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Julia Pinto', legal_identifier: '675.698.723-29', document_type: :cpf,  birth_date: '1946-09-12'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Rafaela Fernandes', legal_identifier: '407.755.150-71', document_type: :cpf,  birth_date: '1957-09-23'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Davi Barbosa', legal_identifier: '769.176.632-81', document_type: :cpf,  birth_date: '1984-06-15'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Felipe Souza', legal_identifier: '288.508.128-56', document_type: :cpf,  birth_date: '1953-10-11'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Davi Barros', legal_identifier: '922.366.590-16', document_type: :cpf,  birth_date: '1948-09-06'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Manuela Barros', legal_identifier: '717.529.943-76', document_type: :cpf,  birth_date: '1947-07-13'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Sophia Lima', legal_identifier: '483.745.965-87', document_type: :cpf,  birth_date: '1986-04-08'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Guilherme Almeida', legal_identifier: '382.202.593-50', document_type: :cpf,  birth_date: '1960-12-01'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Gustavo Correia', legal_identifier: '320.506.285-57', document_type: :cpf,  birth_date: '1969-10-10'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Arthur Azevedo', legal_identifier: '314.254.814-51', document_type: :cpf,  birth_date: '1957-12-05'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Alice Barbosa', legal_identifier: '498.905.245-28', document_type: :cpf,  birth_date: '1978-07-17'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Julia Pinto', legal_identifier: '523.103.251-64', document_type: :cpf,  birth_date: '1986-03-22'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Laura Alves', legal_identifier: '740.887.106-20', document_type: :cpf,  birth_date: '1950-02-07'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Gabriela Costela', legal_identifier: '675.722.172-80', document_type: :cpf,  birth_date: '1960-06-30'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Maria Cunha', legal_identifier: '909.316.456-44', document_type: :cpf,  birth_date: '1988-10-16'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Luiza Cardoso', legal_identifier: '104.749.775-12', document_type: :cpf,  birth_date: '1946-03-30'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Laura Carvalho', legal_identifier: '456.239.979-63', document_type: :cpf,  birth_date: '1956-08-28'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Mariana Souza', legal_identifier: '744.813.814-25', document_type: :cpf,  birth_date: '1988-03-10'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Beatriz Costela', legal_identifier: '484.389.978-76', document_type: :cpf,  birth_date: '1954-07-13'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Isabella Rodrigues', legal_identifier: '114.334.886-45', document_type: :cpf,  birth_date: '1945-10-22'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Beatriz Alves', legal_identifier: '177.710.982-88', document_type: :cpf,  birth_date: '1971-07-17'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Bernardo Martins', legal_identifier: '726.427.622-47', document_type: :cpf,  birth_date: '1984-01-02'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Sophia Correia', legal_identifier: '295.948.784-53', document_type: :cpf,  birth_date: '1986-11-22'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Lucas Almeida', legal_identifier: '992.143.236-97', document_type: :cpf,  birth_date: '1982-06-23'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Mariana Cunha', legal_identifier: '656.490.551-61', document_type: :cpf,  birth_date: '1955-08-01'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Giovanna Ferreira', legal_identifier: '167.336.837-92', document_type: :cpf,  birth_date: '1965-11-27'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Felipe Ribeiro', legal_identifier: '938.726.587-48', document_type: :cpf,  birth_date: '1958-02-26'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Davi Souza', legal_identifier: '230.486.419-79', document_type: :cpf,  birth_date: '1962-09-07'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Miguel Pinto', legal_identifier: '131.861.917-48', document_type: :cpf,  birth_date: '1984-02-01'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Julia Silva', legal_identifier: '683.271.673-47', document_type: :cpf,  birth_date: '1956-11-30'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Lucas Almeida', legal_identifier: '147.945.481-44', document_type: :cpf,  birth_date: '1957-04-26'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Giovanna Barros', legal_identifier: '801.633.727-45', document_type: :cpf,  birth_date: '1990-11-29'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Lucas Costela', legal_identifier: '698.600.345-57', document_type: :cpf,  birth_date: '1989-08-07'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Davi Araújo', legal_identifier: '146.421.104-27', document_type: :cpf,  birth_date: '1982-08-21'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Sophia Ferreira', legal_identifier: '744.740.623-44', document_type: :cpf,  birth_date: '1976-12-06'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Rafaela Pinto', legal_identifier: '939.813.385-87', document_type: :cpf,  birth_date: '1951-03-17'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Manuela Silva', legal_identifier: '945.264.978-16', document_type: :cpf,  birth_date: '1947-07-01'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Mariana Rodrigues', legal_identifier: '966.777.600-16', document_type: :cpf,  birth_date: '1975-08-04'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Rafael Cunha', legal_identifier: '439.959.854-99', document_type: :cpf,  birth_date: '1990-03-14'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Beatriz Pinto', legal_identifier: '318.487.218-99', document_type: :cpf,  birth_date: '1983-09-24'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Rafaela Dias', legal_identifier: '697.841.338-80', document_type: :cpf,  birth_date: '1971-04-16'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Enzo Pereira', legal_identifier: '404.328.251-20', document_type: :cpf,  birth_date: '1943-12-08'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Sophia Fernandes', legal_identifier: '218.314.430-55', document_type: :cpf,  birth_date: '1945-02-25'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Beatriz Barbosa', legal_identifier: '848.803.786-13', document_type: :cpf,  birth_date: '1943-04-15'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Felipe Cardoso', legal_identifier: '663.770.801-53', document_type: :cpf,  birth_date: '1942-09-11'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Rafael Castro', legal_identifier: '508.457.569-21', document_type: :cpf,  birth_date: '1964-07-13'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Beatriz Dias', legal_identifier: '733.671.452-29', document_type: :cpf,  birth_date: '1960-02-26'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Manuela Correia', legal_identifier: '272.582.128-81', document_type: :cpf,  birth_date: '1953-05-05'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Enzo Castro', legal_identifier: '738.570.827-44', document_type: :cpf,  birth_date: '1977-08-05'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Luiza Correia', legal_identifier: '733.941.217-71', document_type: :cpf,  birth_date: '1960-04-25'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Alice Rodrigues', legal_identifier: '230.221.494-67', document_type: :cpf,  birth_date: '1973-01-11'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Enzo Gomes', legal_identifier: '555.559.443-32', document_type: :cpf,  birth_date: '1947-11-14'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Beatriz Castro', legal_identifier: '977.738.946-79', document_type: :cpf,  birth_date: '1966-12-08'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Luiza Rocha', legal_identifier: '712.428.497-84', document_type: :cpf,  birth_date: '1976-09-15'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Sophia Carvalho', legal_identifier: '233.868.317-89', document_type: :cpf,  birth_date: '1950-03-27'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Yasmin Oliveira', legal_identifier: '410.859.147-57', document_type: :cpf,  birth_date: '1973-12-08'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Maria Martins', legal_identifier: '977.109.985-53', document_type: :cpf,  birth_date: '1947-12-17'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Pedro Santos', legal_identifier: '353.548.949-34', document_type: :cpf,  birth_date: '1943-11-18'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Giovanna Pereira', legal_identifier: '558.457.269-14', document_type: :cpf,  birth_date: '1964-05-06'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Pedro Ribeiro', legal_identifier: '147.255.554-99', document_type: :cpf,  birth_date: '1967-07-06'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Lucas Dias', legal_identifier: '976.995.291-12', document_type: :cpf,  birth_date: '1973-05-27'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Felipe Correia', legal_identifier: '359.698.985-87', document_type: :cpf,  birth_date: '1967-08-10'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Matheus Barros', legal_identifier: '861.492.770-45', document_type: :cpf,  birth_date: '1959-12-22'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Laura Costela', legal_identifier: '115.349.972-49', document_type: :cpf,  birth_date: '1948-07-17'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Alice Pinto', legal_identifier: '618.357.373-51', document_type: :cpf,  birth_date: '1946-03-05'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Nicolas Azevedo', legal_identifier: '421.847.536-35', document_type: :cpf,  birth_date: '1975-01-21'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Enzo Cunha', legal_identifier: '610.653.823-55', document_type: :cpf,  birth_date: '1941-06-26'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Pedro Cardoso', legal_identifier: '349.507.595-49', document_type: :cpf,  birth_date: '1979-04-22'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Gabriel Alves', legal_identifier: '215.793.127-87', document_type: :cpf,  birth_date: '1967-07-31'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Guilherme Souza', legal_identifier: '584.690.963-29', document_type: :cpf,  birth_date: '1956-12-15'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Yasmin Alves', legal_identifier: '124.569.740-67', document_type: :cpf,  birth_date: '1951-10-16'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Giovanna Santos', legal_identifier: '561.341.385-20', document_type: :cpf,  birth_date: '1973-09-14'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Bernardo Lima', legal_identifier: '105.910.558-13', document_type: :cpf,  birth_date: '1982-04-06'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Maria Fernandes', legal_identifier: '777.457.821-10', document_type: :cpf,  birth_date: '1966-03-01'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Rafaela Lima', legal_identifier: '410.232.331-25', document_type: :cpf,  birth_date: '1946-08-28'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Davi Carvalho', legal_identifier: '712.834.269-36', document_type: :cpf,  birth_date: '1984-06-05'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Nicolas Castro', legal_identifier: '622.467.942-88', document_type: :cpf,  birth_date: '1987-03-01'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Matheus Ribeiro', legal_identifier: '227.150.514-55', document_type: :cpf,  birth_date: '1990-07-18'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Davi Costela', legal_identifier: '315.332.140-17', document_type: :cpf,  birth_date: '1978-02-19'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Rafaela Rodrigues', legal_identifier: '790.810.629-44', document_type: :cpf,  birth_date: '1980-09-14'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Arthur Rocha', legal_identifier: '192.563.827-29', document_type: :cpf,  birth_date: '1963-12-30'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Alice Pinto', legal_identifier: '304.234.430-10', document_type: :cpf,  birth_date: '1942-06-05'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Gabriel Melo', legal_identifier: '355.797.205-89', document_type: :cpf,  birth_date: '1974-11-26'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Sophia Pereira', legal_identifier: '295.300.405-28', document_type: :cpf,  birth_date: '1963-05-25'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Matheus Souza', legal_identifier: '405.386.761-76', document_type: :cpf,  birth_date: '1985-04-03'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Felipe Carvalho', legal_identifier: '116.623.138-91', document_type: :cpf,  birth_date: '1960-09-11'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Alice Pinto', legal_identifier: '222.934.545-17', document_type: :cpf,  birth_date: '1988-01-05'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Manuela Fernandes', legal_identifier: '291.483.172-64', document_type: :cpf,  birth_date: '1967-08-21'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Mariana Gomes', legal_identifier: '273.435.320-86', document_type: :cpf,  birth_date: '1961-01-14'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Giovanna Santos', legal_identifier: '900.794.310-85', document_type: :cpf,  birth_date: '1989-05-15'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Gustavo Rocha', legal_identifier: '618.571.832-77', document_type: :cpf,  birth_date: '1942-04-25'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Giovanna Araújo', legal_identifier: '394.700.816-28', document_type: :cpf,  birth_date: '1950-02-07'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Gabriel Costela', legal_identifier: '680.462.172-86', document_type: :cpf,  birth_date: '1955-09-19'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Manuela Rocha', legal_identifier: '433.800.244-20', document_type: :cpf,  birth_date: '1954-12-22'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Beatriz Souza', legal_identifier: '813.295.810-88', document_type: :cpf,  birth_date: '1965-03-02'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Julia Castro', legal_identifier: '259.104.530-33', document_type: :cpf,  birth_date: '1942-07-11'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Davi Carvalho', legal_identifier: '644.798.586-16', document_type: :cpf,  birth_date: '1951-02-11'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Nicolas Costela', legal_identifier: '514.444.924-75', document_type: :cpf,  birth_date: '1970-05-02'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Rafaela Martins', legal_identifier: '173.377.343-45', document_type: :cpf,  birth_date: '1965-01-10'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Bernardo Pinto', legal_identifier: '917.771.775-56', document_type: :cpf,  birth_date: '1964-11-20'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Felipe Martins', legal_identifier: '308.925.316-73', document_type: :cpf,  birth_date: '1987-01-15'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Nicolas Barros', legal_identifier: '461.568.952-42', document_type: :cpf,  birth_date: '1943-06-05'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Julia Azevedo', legal_identifier: '601.637.942-35', document_type: :cpf,  birth_date: '1945-10-28'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Laura Araújo', legal_identifier: '177.773.658-36', document_type: :cpf,  birth_date: '1978-04-29'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Sophia Castro', legal_identifier: '625.544.242-15', document_type: :cpf,  birth_date: '1986-05-12'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Beatriz Azevedo', legal_identifier: '771.901.480-64', document_type: :cpf,  birth_date: '1958-08-18'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Rafaela Ferreira', legal_identifier: '363.657.677-29', document_type: :cpf,  birth_date: '1967-03-04'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Matheus Azevedo', legal_identifier: '440.997.198-83', document_type: :cpf,  birth_date: '1953-05-20'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Julia Pinto', legal_identifier: '421.798.733-57', document_type: :cpf,  birth_date: '1941-06-24'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Gustavo Correia', legal_identifier: '344.286.600-92', document_type: :cpf,  birth_date: '1967-01-20'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Gabriela Castro', legal_identifier: '490.572.828-52', document_type: :cpf,  birth_date: '1984-06-04'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Bernardo Alves', legal_identifier: '636.667.155-32', document_type: :cpf,  birth_date: '1983-02-05'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Luiza Barbosa', legal_identifier: '720.541.576-32', document_type: :cpf,  birth_date: '1989-01-11'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Matheus Rocha', legal_identifier: '381.265.475-79', document_type: :cpf,  birth_date: '1943-09-26'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Manuela Almeida', legal_identifier: '667.914.132-36', document_type: :cpf,  birth_date: '1948-09-27'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Julia Alves', legal_identifier: '756.667.846-17', document_type: :cpf,  birth_date: '1991-11-14'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Lucas Silva', legal_identifier: '711.558.201-43', document_type: :cpf,  birth_date: '1971-05-02'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Yasmin Castro', legal_identifier: '431.670.532-55', document_type: :cpf,  birth_date: '1946-03-27'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Luiza Ribeiro', legal_identifier: '596.953.350-34', document_type: :cpf,  birth_date: '1947-10-17'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Lucas Castro', legal_identifier: '838.786.373-38', document_type: :cpf,  birth_date: '1978-05-27'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Laura Almeida', legal_identifier: '289.992.787-70', document_type: :cpf,  birth_date: '1954-02-01'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Beatriz Costela', legal_identifier: '838.806.447-27', document_type: :cpf,  birth_date: '1962-08-28'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Arthur Ferreira', legal_identifier: '821.722.372-47', document_type: :cpf,  birth_date: '1953-07-06'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Arthur Gomes', legal_identifier: '738.226.733-74', document_type: :cpf,  birth_date: '1969-03-23'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Lucas Costela', legal_identifier: '540.484.953-66', document_type: :cpf,  birth_date: '1979-05-30'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Pedro Silva', legal_identifier: '705.516.957-19', document_type: :cpf,  birth_date: '1980-11-21'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Giovanna Correia', legal_identifier: '799.585.763-99', document_type: :cpf,  birth_date: '1983-11-03'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Miguel Ribeiro', legal_identifier: '504.992.841-56', document_type: :cpf,  birth_date: '1970-05-28'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Gabriel Oliveira', legal_identifier: '563.740.552-17', document_type: :cpf,  birth_date: '1988-04-07'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Arthur Oliveira', legal_identifier: '805.593.829-96', document_type: :cpf,  birth_date: '1971-12-19'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Gabriela Costela', legal_identifier: '308.850.128-16', document_type: :cpf,  birth_date: '1947-12-20'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Beatriz Pinto', legal_identifier: '921.924.901-61', document_type: :cpf,  birth_date: '1988-07-19'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Manuela Dias', legal_identifier: '578.570.926-17', document_type: :cpf,  birth_date: '1960-06-03'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Gabriela Rodrigues', legal_identifier: '123.121.252-64', document_type: :cpf,  birth_date: '1962-04-16'  , role: 'Empregado',uses_medication: false, gender:"F"})
Donor.create({company_id: 2, name: 'Rafaela Souza', legal_identifier: '527.574.765-86', document_type: :cpf,  birth_date: '1954-06-14'  , role: 'Empregado',uses_medication: false, gender:"F"})

# testes

TestType.create({name:"Anfetamina / Rebite / Bolinha",short_name:"AMP",description:"",collected_material:"Urina ou Saliva"})
TestType.create({name:"Antidepressivos Tricíclicos",short_name:"TCA",description:"",collected_material:"Urina ou Saliva"})
TestType.create({name:"Barbitúrico / Sedativo / Anestésico",short_name:"BAR",description:"",collected_material:"Urina ou Saliva"})
TestType.create({name:"Benzodiazepina / Tranquilizante",short_name:"BZO",description:"",collected_material:"Urina ou Saliva"})
TestType.create({name:"Cocaína / Crack / Merla",short_name:"COC",description:"",collected_material:"Urina ou Saliva"})
TestType.create({name:"Ecstasy / Bala",short_name:"MDMA",description:"",collected_material:"Urina ou Saliva"})
TestType.create({name:"Fenciclidina / Pó de anjo",short_name:"PCP",description:"",collected_material:"Urina ou Saliva"})
TestType.create({name:"Maconha / Haxixe",short_name:"THC",description:"",collected_material:"Urina ou Saliva"})
TestType.create({name:"Metadona / Analgésico",short_name:"MTD",description:"",collected_material:"Urina ou Saliva"})
TestType.create({name:"Metanfetamina / Crystal",short_name:"MET",description:"",collected_material:"Urina ou Saliva"})
TestType.create({name:"Morfina / Opióides - Ópio / Heroína",short_name:"MOP",description:"",collected_material:"Urina ou Saliva"})
TestType.create({name:"Opiáceos",short_name:"OPI",description:"",collected_material:"Urina ou Saliva"})
TestType.create({name:"Nicotina",short_name:"Nicotina",description:"",collected_material:"Urina ou Saliva"})
TestType.create({name:"Álcool",short_name:"Álcool",description:"",collected_material:"Urina ou Saliva"})
